config/routes.rb
Ribbot::Application.routes.draw do
  
  scope '/issues/:issue_id/' do
    resources :proposals do
      resources :procons
    end
  end
  resources :issues 
  
  resources :proposals
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_issue
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages

  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end

  namespace :superuser do
    resources :issues
  end

  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'

  constraints(Subdomain) do
    match '/' => 'posts#index'
  end

  root :to => 'users#new'

end

app/models/issue.rb
class Issue
  include Mongoid::Document
  include Mongoid::Timestamps

  POST_OPTIONS = {
    text_or_url: 0,
    url_or_text: 1,
    text_only:   2,
    url_only:    3
  }

  field :description, type: String
  field :title, type: String
  #field :post_options, type: Integer, default: POST_OPTIONS[:text_or_url]

  field :post_label, type: String, default: "Post"
  field :posts_label, type: String, default: "Posts"
  field :new_post_label, type: String, default: "New Post"

  has_many :proposals
  has_many :participations, :dependent => :destroy
  has_many :tags
  has_many :pages
  belongs_to :theme
  belongs_to :user, index: true

  def add_member user
    if p = participations.where(:user_id => user.id).first
      p.update_attribute :hidden, false if p.hidden?
    else
      participations.create!(:user => user, :level => Participation::MEMBER)
    end
  end

  def add_admin user
    participations.create!(:user => user, :level => Participation::ADMIN)
  end

  def add_owner user
    participations.create!(:user => user, :level => Participation::OWNER)
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!, :except => :show

  def new
    @issue = Issue.new
  end

  def index
    @participations = current_user.participations.includes(:issue).where(:hidden => false).asc(:level)
  end

  def create
    debugger
    @issue = Issue.new(params[:issue])
    if @issue.save
      @issue.add_owner(current_user)
      redirect_to issues_path, :notice => "Issue created!"
    else
      render :new
    end
  end

  def edit
    @issue = Issue.find(params[:id])
    if @issue.save
      redirect_to issues_path, :notice => "Issue revised!"
    else
      render :edit
    end
  end

  def show
    @issue = Issue.find(params[:id])
    redirect_to proposals_url @issue
  end

  def destroy
    @issue = Issue.find(params[:id])
    authorize! :destroy, @issue
    @issue.destroy
    redirect_to issues_path, :notice => "Issue deleted."
  end

end

app/views/issues/_form.html.erb
<%= form_for @issue, :url => @issue.new_record? ? issues_path : issue_path(@issue), :html => {:class => "form-stacked"} do |f| %>
  <p><h2>Create A Issue</h2></p>
  <% if @issue.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @issue.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Note: names can be changed later or used on a custom domain</p>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span8" %>
    <%= f.label :description %>
    <%= f.text_area :description, :class => "span8" %>
  </p>


  <fieldset>
    <%= submit_tag "Create Issue", :class => "btn btn-primary btn-large", :disable_with => "Creating..." %>
  </fieldset>
<% end %>

app/views/issues/edit.html.erb
<%= render :partial => 'form' %>

app/views/issues/index.html.erb
<div class='pull-right'>
  <%= link_to '+ Create An Issue', new_issue_path, :class => "btn btn-primary" %>
</div>
<h1>Issues</h1>
<br/>

<table class="table">
  <tbody>
    <% @participations.each do |p| %>
      <% f = p.issue %>
      <% next if f.nil? %>
      <tr>
        <td><h3><%= link_to f.title, issue_path(f) %></h3></td>
        <td><p></p><%= p.level_in_words %></td>
        <td>
          <% if p.level == Participation::MEMBER %>
            <%= link_to "Hide", hide_participation_path(p), :method => :put, :class => 'btn' %>
          <% end %>
          <%= link_to "Edit", edit_issue_path(f), :class => 'btn' if can?(:edit, f) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issues/new.html.erb
<%= form_for @issue, :html => {:class => "form-stacked"} do |f| %>
  <p><h2>Create A Issue</h2></p>
  <% if @issue.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @issue.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Note: names can be changed later or used on a custom domain</p>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span8" %>
    <%= f.label :description %>
    <%= f.text_area :description, :class => "span8" %>
  </p>


  <fieldset>
    <%= submit_tag "Create Issue", :class => "btn btn-primary btn-large", :disable_with => "Creating..." %>
  </fieldset>
<% end %>

app/views/issues/show.html.erb
    <h2><%= @issue.title %></h2>
    <h2><%= @issue.description %></h2>
    <p>Proposals will come below</p>