config/routes.rb
Ribbot::Application.routes.draw do
  
  scope '/issues/:issue_id/' do
    resources :proposals do
      resources :procons
    end
  end
  resources :issues 
  
  resources :proposals
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_issue
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages

  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end

  namespace :superuser do
    resources :issues
  end

  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'

  constraints(Subdomain) do
    match '/' => 'posts#index'
  end

  root :to => 'users#new'

end

app/models/procon.rb
class Procon
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongo::Voteable
  acts_as_nested_set
  include MarkdownProcessor
  
  field :text, type: String
  field :html, type: String
  field :deleted, type: Boolean, default: false
  field :ranking, type: Float, default: 0.0
  field :yepnope, type: Boolean, default: true
  
  index :ranking
  index :'votes.point'

  belongs_to :user, index: true
  belongs_to :proposal, index: true
  belongs_to :issue, index: true
  
  validates_presence_of :text, :user, :proposal
  validate :user_is_not_banned
  
  voteable self, :up => +1, :down => -1
  
  before_save  :process_markdown
  before_save  :create_participation
  after_create  :inc_procon_count
  after_destroy :dec_procon_count
  
  attr_protected :parent_id
  
  def create_participation
    self.issue.add_member(user)
  end
  
  def inc_procon_count
    if self.yepnope
      proposal.inc(:pro_count, 1)
    else
      proposal.inc(:con_count, 1)
    end
  end
  
  def dec_procon_count(yepnope)
    if self.yepnope
      proposal.inc(:pro_count, -1)
    else
      proposal.inc(:con_count, -1)
    end
  end
  
  def user_is_not_banned
    errors.add(:base, "You can no longer participate in this forum") if user.banned_from?(proposal)
  end
  
  def update_ranking
    if votes_point <= 0
      self.update_attribute :ranking, votes_point
    else
      self.update_attribute :ranking, ci_lower_bound(up_votes_count, votes_count)
    end
    reorder
  end
  
  # http://www.evanmiller.org/how-not-to-sort-by-average-rating.html
  def ci_lower_bound(pos, n, confidence=0.95)
    return 0 if n == 0
    z = 1.96 # Statistics2.pnormaldist(1-(1-confidence)/2)
    phat = 1.0*pos/n
    (phat + z*z/(2*n) - z * Math.sqrt((phat*(1-phat)+z*z/(4*n))/n))/(1+z*z/n)
  end
  
  # insertion sort to fixed the nested set when ranking changes
  def reorder
    sibs = siblings
    return if sibs.empty?
    sibs.each do |s|
      if self.ranking >= s.ranking
        self.move_to_left_of(s) and return
      end
    end
    self.move_to_right_of(sibs.last)
  end
end

app/controllers/procons_controller.rb
class ProconsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_params
  
  def load_params
    @proposal = Proposal.find(params[:proposal_id])
    @procons = @proposal.procons.find(params[:id]) if params[:id].present?
  end
  
  def create
    @issue = Issue.find(params[:issue_id])
    @procon = @proposal.procons.new(params[:procon])
    @procon.issue = @issue
    @procon.user = current_user
    @procon.parent = @proposal.procons.find(params[:procon][:parent_id]) unless params[:procon][:parent_id].blank?
    respond_to do |format|
      format.html do
        if @procon.save
          redirect_to proposal_path(@issue, @proposal), :notice => "procon proposaled!"
        else
          redirect_to proposal_path(@procon.proposal)
        end
      end
      format.js
    end
  end
  
  def update
    authorize! :update, @procon
    if @procon.update_attributes(params[:procon])
      redirect_to proposal_path(@proposal), :notice => "Updated!"
    else
      render :edit
    end
  end
  
  def edit
    authorize! :edit, @procon
  end
  
  def destroy
    if @procon.children.empty? or current_user.admin_of?(@procon.forum)
      @procon.destroy
    else
      @procon.update_attribute :deleted, true
    end
    redirect_to @proposal, :notice => "#{current_forum.procon_label} deleted"
  end
end

app/views/procons/_form_con.html.erb
<% reply_procon ||= false %>

<%= form_for @procon, :url => proposal_procons_path(@issue, @proposal), :remote => reply_procon, :html => {:class => "procon-form", :id => 'addcon-form'  } do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :yepnope, :value => false %>

  <%= render 'shared/error_messages', :target => @proposal %>
  <%= render 'shared/error_messages', :target => @procon %>

  <p><%= f.text_area :text, :class => "span6", :rows => '5' %></p>
  <p>
    
  </p>
  <p>
    <% button_text = @procon.new_record? ? 'Submit' : 'Save Changes' %>
    <%= submit_tag button_text, :class => "btn btn-primary", :disable_with => button_text, :disabled => !signed_in? %>

    <% if reply_procon %>
      <%= link_to "cancel", '#', :class => "cancel-link btn" %>
    <% end %>

    <% if not signed_in? %>
      <%= link_to "Sign in or create an account", signin_path %> to discuss.
    <% end %>
  </p>
<% end %>

app/views/procons/_form_pro.html.erb
<% reply_procon ||= false %>

<%= form_for @procon, :url => proposal_procons_path(@issue, @proposal), :remote => reply_procon, :html => {:class => "procon-form", :id => 'addpro-form' } do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :yepnope, :value => true %>

  <%= render 'shared/error_messages', :target => @proposal %>
  <%= render 'shared/error_messages', :target => @procon %>

  <p><%= f.text_area :text, :class => "span6", :rows => '5' %></p>
  <p>
    
  </p>
  <p>
    <% button_text = @procon.new_record? ? 'Submit' : 'Save Changes' %>
    <%= submit_tag button_text, :class => "btn btn-primary", :disable_with => button_text, :disabled => !signed_in? %>

    <% if reply_procon %>
      <%= link_to "cancel", '#', :class => "cancel-link btn" %>
    <% end %>

    <% if not signed_in? %>
      <%= link_to "Sign in or create an account", signin_path %> to discuss.
    <% end %>
  </p>
<% end %>

app/views/procons/_procon.html.erb
<%
  indent            = true  if local_assigns[:indent].nil?
  show_proposal_link    = false if local_assigns[:show_proposal_link].nil?
  show_links        = true  if local_assigns[:show_links].nil?
  voting            = true  if local_assigns[:voting].nil?
%>

<div class="procon">
  <div class="show">
    <%- # render :partial => 'shared/byline', :locals => {:procon_or_proposal => procon, :show_proposal_link => show_proposal_link, :voting => voting} %>
  
    <% if procon.deleted %>
      <p><small>[deleted]</small></p>
    <% else %>
      <%= render :partial => 'votes/js_counter' %>
      <%= procon.html.html_safe %>
  
      <% if show_links %>
        <p>
          <%= link_to 'reply', '#', :class => "reply-link" %>
          <% if can? :edit, procon %>
            <%= link_to 'edit', edit_proposal_procon_path(@proposal, procon) %>
          <% end %>
          <% if can? :destroy, procon %>
            <%= link_to 'delete', proposal_procon_path(@proposal, procon), :method => :delete, :confirm => "Are you sure you want to delete?" %>
          <% end %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/procons/create.js.erb
$('#comment_<%= @comment.parent.id %> form').remove();
<% if @comment.save %>
  $('#comment_<%= @comment.parent.id %>').after("<%= escape_javascript(render @comment) %>");
<% end %>

app/views/procons/edit.html.erb
<%= render 'form' %>