config/routes.rb
Ribbot::Application.routes.draw do
  
  scope '/issues/:issue_id/' do
    resources :proposals do
      resources :procons
    end
  end
  resources :issues 
  
  resources :proposals
  resources :votes
  resources :users do
    member do
      put :password_reset
    end
    collection do
      post :create_with_issue
    end
  end
  resources :participations do
    member do
      put :ban
      put :unban
      put :hide
    end
  end
  resources :themes
  resources :pages

  namespace :account do
    resources :comments
    resources :posts
    resource  :profile
    resources :users
    resources :settings
    resources :tags do
      post :sort, :on => :collection
    end
    resources :pages do
      post :sort, :on => :collection
    end
    resources :themes do
      post :install, :on => :member
      post :uninstall, :on => :collection
    end
    resource :ownership
    resource :domain
  end

  namespace :superuser do
    resources :issues
  end

  resources :verifications
  resources :password_resets
  resources :sessions

  match 'signin' => "sessions#new"
  match 'signout' => "sessions#destroy", :via => :delete
  match 'features' => 'static#features'
  match 'pricing' => 'static#pricing'

  constraints(Subdomain) do
    match '/' => 'posts#index'
  end

  root :to => 'users#new'

end

app/models/issue.rb
class Issue
  include Mongoid::Document
  include Mongoid::Timestamps

  POST_OPTIONS = {
    text_or_url: 0,
    url_or_text: 1,
    text_only:   2,
    url_only:    3
  }

  field :description, type: String
  field :title, type: String
  #field :post_options, type: Integer, default: POST_OPTIONS[:text_or_url]

  field :post_label, type: String, default: "Post"
  field :posts_label, type: String, default: "Posts"
  field :new_post_label, type: String, default: "New Post"

  has_many :proposals
  has_many :participations, :dependent => :destroy
  has_many :tags
  has_many :pages
  belongs_to :theme
  belongs_to :user, index: true

  def add_member user
    if p = participations.where(:user_id => user.id).first
      p.update_attribute :hidden, false if p.hidden?
    else
      participations.create!(:user => user, :level => Participation::MEMBER)
    end
  end

  def add_admin user
    participations.create!(:user => user, :level => Participation::ADMIN)
  end

  def add_owner user
    participations.create!(:user => user, :level => Participation::OWNER)
  end

end

app/models/proposal.rb
require 'uri'

class Proposal 
  include Mongoid::Document
  include Mongoid::Timestamps
  include Sunspot::Mongoid
  include Mongo::Voteable
  include GravityRanking
  include MarkdownProcessor
  
  field :title, type: String
  field :url, type: String, index: true
  field :text, type: String
  field :html, type: String
  field :ranking, type: Float, default: 0.0
  field :pro_count, type: Integer, default: 0
  field :con_count, type: Integer, default: 0
  field :description, type: String
  
  index :ranking
  index :'votes.point'

  belongs_to :user, index: true
  belongs_to :issue, index: true
  has_many :procons, dependent: :destroy
  has_and_belongs_to_many :tags, inverse_of: nil, index: true

  validates_presence_of :description, :title
  
  voteable self, :up => +1, :down => -1
  
  before_save   :process_markdown
  after_create  :create_participation
  after_save    :update_post_counts
  after_destroy :update_post_counts
  
  searchable do
    text :title, :boost => 2.0, :stored => true
    text :url, :stored => true
    text :text, :stored => true
    text :procons_texts do
      procons.collect {|c| c.text }
    end
    string :issue_id, :references => Issue
    string :tag_ids, :multiple => true
  end
  
  def create_participation
    @issue = self.issue
    @issue.add_member(user)
  end
  
  def user_is_not_banned
    errors.add(:base, "You can no longer participate in this issue") if user.banned_from?(issue)
  end
  
  def update_post_counts
    if tag_ids_changed?
      tags.each do |t|
        t.update_attribute :posts_count, Post.all_in(:tag_ids => [t.id]).count
      end
    end
  end
  
  def self.with_tags names, issue
    if names.blank?
      scoped
    else
      names = names.split(',')
      tags = issue.tags.all_in(:name => names)
      all_in(:tag_ids => tags.collect{|t| t.id})
    end
  end
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def new
    @proposal = Proposal.new(params[:proposal])
  end
  
  def create
    @issue = Issue.find(params[:issue_id])
    @proposal = Proposal.new(params[:proposal])
    @proposal.issue = @issue
    @proposal.user = current_user
    if @proposal.save      
      current_user.vote(@proposal, :up)
      @proposal.update_ranking
      redirect_to proposal_path(@issue, @proposal), :notice => "Proposal created!"
    else
      render :new
    end
  end
  
  def index
    @issue = Issue.find(params[:issue_id])
    if params[:search].present?
      @proposals = Proposal.solr_search do
        keywords params[:search]
        with :issue_id, @issue.id.to_s
        paginate :page => params[:page]
      end
    else
      @proposals = @issue.proposals.with_tags(params[:tags], @issue).where(:'votes.point'.gt => -5).page(params[:page])
      
      if params[:sort] == 'top'
        @proposals = @proposals.desc('votes.point')
      elsif params[:sort] == 'latest'
        @proposals = @proposals.desc(:created_at)
      else
        @proposals = @proposals.desc(:ranking)
      end            
    end
  end
  
  def show
    @issue = Issue.find(params[:issue_id])
    @proposal = Proposal.find(params[:id])
    @cons = @proposal.procons.where(:yepnope => false)
    @pros = @proposal.procons.where(:yepnope => true)
    @procon = Procon.new(params[:procon])
    if @proposal.nil?
      redirect_to root_path, :notice => "That proposal is no longer available."
      return
    end
    # @comment = @proposal.comments.new
    # @comments = @proposal.comments.asc(:lft).where(:'votes.point'.gt => -5).page(params[:page])
  end
  
  def edit
    @proposal = Proposal.find(params[:issue_id])
    authorize! :edit, @proposal
  end
  
  def update
    params[:proposal][:tag_ids] ||= []
    @proposal = current_issue.proposals.find(params[:id])
    authorize! :update, @proposal
    if @proposal.update_attributes(params[:proposal])
      redirect_to @proposal, :notice => "Proposal updated!"
    else
      render :edit
    end
  end
  
  def destroy
    @proposal = Proposal.find(params[:id])
    authorize! :destroy, @proposal
    @proposal.destroy
    redirect_to root_path, :notice => "Proposal deleted!"
  end
  
end

app/views/proposals/_form.html.erb
<%= form_for @proposal, :html => {:class => "proposal-form form-stacked"} do |f| %>
  <h2>New Proposal</h2><br/>
  
  <%= render 'shared/error_messages', :target => @proposal %>
  
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span8" %>
    <%= f.label :description %>
    <%= f.text_area :description, :class => "span8" %>
  </p>
  
  
  <% if @proposal.tags.present? %>
    <p>
      <%= f.label :tag_ids, 'Tags' %>
      <% current_forum.tags.each do |tag| %>
        <span>
          <% on = @proposal.tags.include?(tag) %>
          <%= check_box_tag "proposal[tag_ids][]", tag.id, on, :class => "tag-checkbox" %>
          <%= link_to tag.name, '#', :class => "tag #{'active' if on} tag-link" %>
        </span>
      <% end %>
    </p>
  <% end %>
  
  <div class="form-actions">
    <% if @proposal.new_record? %>
      <%= submit_tag "Submit", :class => "btn btn-primary", :disable_with => "Submitting..." %> &nbsp; <%= link_to "Cancel", :back, :class => "btn" %>
    <% else %>
      <%= submit_tag "Save Changes", :class => "btn btn-primary", :disable_with => "Saving..." %> &nbsp; <%= link_to "Cancel", :back, :class => "btn" %>
    <% end %>
  </div>
<% end %>

app/views/proposals/_proposal.html.erb
<% @proposals.each do |prop| %>
  <%
    voting = true if local_assigns[:voting].nil?
  %>

  <tr class="post">
    <% if voting %>
      <td class="voting">
        <%= render :partial => 'votes/js_counter' %>
        <%-# render :partial => 'votes/vote', :locals => {:voteable => prop} %>
      </td>
    <% end %>
    
    <td class="description">
      <div class="pull-right">
        <% prop.tags.each do |t| %>
          <%= tag_link t %>
        <% end %>
      </div>
        <h3><%= link_to prop.title, proposal_path(@issue, prop), :rel => 'nofollow', :class => 'post-link' %></h3>
      <%- # render :partial => 'shared/byline', :locals => {:comment_or_proposal => prop, :show_comments_link => true, :prop => prop} %>
    </td>
  </tr>
<% end %>

app/views/proposals/index.html.erb
<ul class="breadcrumb" style="margin-top:-18px;">
      <li>
        <%= link_to 'Issues', issues_path %> <span class="divider">/</span>
      </li>
      <li>
        <%= link_to @issue.title, issue_path(@issue) %> <span class="divider">/</span>
      </li>
    </ul>
<div class="row">
  <h1 class="title"><span style="color:grey">Issue: </span><%= @issue.title %></h1>
  <h3 class="description"><%= @issue.description %></h3>
  
  <div class="span9">
    
    <%= link_to 'New proposal', new_proposal_path, :class => "btn btn-primary leading" %>
    <%= form_tag proposals_path, :method => :get, :class => 'form-inline pull-right' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :class => "btn", :disable_with => "Search" %>
      <% if params[:search].present? %>
        &nbsp;<%= link_to 'clear', root_path %>
      <% end %>
    <% end %>

    <% if @proposals.empty? and @issue.proposals.empty? %>
      <div class="alert-message block-message success">
        <p><strong>Welcome! This is a brand new forum</strong></p>
        <p>To get started try adding the first proposal.</p>
        <div class="alert-actions">
          <%= link_to 'New Proposal', new_proposal_path, :class => "btn" %>
        </div>
      </div>
    <% elsif @proposals.empty? %>
      <div class="alert-message block-message info no-results">
        <p><strong>Your search didn't return an results!</strong></p>
        <p>Please try a new search or <%= link_to 'go back', root_path %>.</p>
      </div>
    <% else %>
    
   <h1>Proposals</h1>
   
    <% if params[:search].present? %>
      <table class="table table-striped">
        <%= render @proposals.results %>
      </table>
    <% else %>
      <ul class="nav nav-tabs">
        <li class="<%= 'active' if params[:sort].blank? %>"><%= link_to 'Popular', proposals_path(request.query_parameters.merge(:sort => nil)) %></li>
        <li class="<%= 'active' if params[:sort] == 'top' %>"><%= link_to 'Top', proposals_path(request.query_parameters.merge(:sort => 'top')) %></li>
        <li class="<%= 'active' if params[:sort] == 'latest' %>"><%= link_to 'Latest', proposals_path(request.query_parameters.merge(:sort => 'latest')) %></li>
      </ul>
      <table class="table table-striped">        
        <%= render 'proposal' %>
      </table>
    <% end %>

      <%= paginate @proposals %>
    <% end %>
  </div>
  <div class="span3" style="padding-top: 68px;">
    <%= render 'shared/tags' %>
  </div>
</div>

app/views/proposals/new.html.erb
<%= render 'form' %>

app/views/proposals/show.html.erb
<ul class="breadcrumb" style="margin-top:-18px;">
      <li>
        <%= link_to 'Issues', issues_path %> <span class="divider">/</span>
      </li>
      <li>
        <%= link_to @issue.title, issue_path(@issue) %> <span class="divider">/</span>
      </li>
      <li>
        <%= link_to 'Proposals', proposals_path(@issue, @proposal) %> <span class="divider">/</span>
      </li>
    </ul>
  <div class="proposal" %>
  <div class="issue span12" style="margin-bottom:20px;">
    <h3><span style="color:grey">Issue:</span> <%= link_to @issue.title.titlecase, issue_path(@issue) %></h3>
    
  </div>
  <div class="proposal span12">
    <h2 class="title" style="color:grey">Proposal: </h2>
    <h2 class="title" style="margin-bottom:30px;"><%= @proposal.title %></h2>
    <p class="description"><%= @proposal.description %></p>
  </div>
  <%- # render :partial => 'shared/byline', :locals => {:comment_or_proposal => @proposal, :voting => true, :show_tags => true} %>
  <%= @proposal.html.html_safe if @proposal.html.present? %>
  <p class="span9">
    <% if can? :edit, @proposal %>
      <%= link_to 'edit', edit_proposal_path(@proposal) %>
    <% end %>
    <% if can? :destroy, @proposal %>
      <%= link_to 'delete', proposal_path(@proposal), :method => :delete, :confirm => "Are you really sure you want to delete this proposal?  This will delete any comments as well." %>
    <% end %>
  </p>
</div>

<hr/>

<div class="row">

  
  <div class="span6"> 
    <h2>Pros</h2> 
    <%= render :partial => 'procons/form_pro' %>  
    <section id="pros">
      <%= render @pros %>
    </section>
  </div>
  
  <div class="span6">
    <h2>Cons</h2>
    <%= render :partial => 'procons/form_con' %>   
    <section id="cons">
      <%= render @cons %>
    </section>
  </div>
  
    <div id="reply_comment" style="display: none;">
      <%- # render :partial => "procons/form", :locals => {:reply_comment => true} %>
    </div>

  </div>
  <div class="span6">
  </div>
</div>